// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface BooleanResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.BooleanRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
