// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface BooleanReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.BooleanReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
