// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dd.proto

package org.DS.project.EBankGRPC;

public interface ddRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.ddResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dname = 4;</code>
   */
  java.lang.String getDname();
  /**
   * <code>string dname = 4;</code>
   */
  com.google.protobuf.ByteString
      getDnameBytes();

  /**
   * <code>bool status = 5;</code>
   */
  boolean getStatus();

  /**
   * <code>int32 amount = 6;</code>
   */
  int getAmount();
}
