// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dd.proto

package org.DS.project.EBankGRPC;

public interface ddRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.ddResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sname = 4;</code>
   */
  java.lang.String getSname();
  /**
   * <code>string sname = 4;</code>
   */
  com.google.protobuf.ByteString
      getSnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 helpful = 6;</code>
   */
  int getHelpful();

  /**
   * <code>int32 frequency = 7;</code>
   */
  int getFrequency();
}
