// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.Empty)
    com.google.protobuf.MessageOrBuilder {
}
