// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package org.DS.project.EBankGRPC;

public interface phoneRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.phoneResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pname = 4;</code>
   */
  java.lang.String getPname();
  /**
   * <code>string pname = 4;</code>
   */
  com.google.protobuf.ByteString
      getPnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string app = 6;</code>
   */
  java.lang.String getApp();
  /**
   * <code>string app = 6;</code>
   */
  com.google.protobuf.ByteString
      getAppBytes();

  /**
   * <code>int32 battery = 7;</code>
   */
  int getBattery();
}
