// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statement.proto

package org.DS.project.EBankGRPC;

public interface statementRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.statementResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sname = 4;</code>
   */
  java.lang.String getSname();
  /**
   * <code>string sname = 4;</code>
   */
  com.google.protobuf.ByteString
      getSnameBytes();

  /**
   * <code>bool status = 5;</code>
   */
  boolean getStatus();

  /**
   * <code>string stype = 6;</code>
   */
  java.lang.String getStype();
  /**
   * <code>string stype = 6;</code>
   */
  com.google.protobuf.ByteString
      getStypeBytes();

  /**
   * <code>bool sendOptOut = 7;</code>
   */
  boolean getSendOptOut();
}
