// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statement.proto

package org.DS.project.EBankGRPC;

/**
 * Protobuf type {@code EBankGRPC.statementResp}
 */
public  final class statementResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EBankGRPC.statementResp)
    statementRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use statementResp.newBuilder() to construct.
  private statementResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private statementResp() {
    sname_ = "";
    status_ = false;
    stype_ = "";
    sendOptOut_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private statementResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            sname_ = s;
            break;
          }
          case 40: {

            status_ = input.readBool();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            stype_ = s;
            break;
          }
          case 56: {

            sendOptOut_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.DS.project.EBankGRPC.StatementServiceImpl.internal_static_EBankGRPC_statementResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.DS.project.EBankGRPC.StatementServiceImpl.internal_static_EBankGRPC_statementResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.DS.project.EBankGRPC.statementResp.class, org.DS.project.EBankGRPC.statementResp.Builder.class);
  }

  public static final int SNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object sname_;
  /**
   * <code>string sname = 4;</code>
   */
  public java.lang.String getSname() {
    java.lang.Object ref = sname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sname_ = s;
      return s;
    }
  }
  /**
   * <code>string sname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSnameBytes() {
    java.lang.Object ref = sname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private boolean status_;
  /**
   * <code>bool status = 5;</code>
   */
  public boolean getStatus() {
    return status_;
  }

  public static final int STYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object stype_;
  /**
   * <code>string stype = 6;</code>
   */
  public java.lang.String getStype() {
    java.lang.Object ref = stype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stype_ = s;
      return s;
    }
  }
  /**
   * <code>string stype = 6;</code>
   */
  public com.google.protobuf.ByteString
      getStypeBytes() {
    java.lang.Object ref = stype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDOPTOUT_FIELD_NUMBER = 7;
  private boolean sendOptOut_;
  /**
   * <code>bool sendOptOut = 7;</code>
   */
  public boolean getSendOptOut() {
    return sendOptOut_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sname_);
    }
    if (status_ != false) {
      output.writeBool(5, status_);
    }
    if (!getStypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stype_);
    }
    if (sendOptOut_ != false) {
      output.writeBool(7, sendOptOut_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sname_);
    }
    if (status_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, status_);
    }
    if (!getStypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stype_);
    }
    if (sendOptOut_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, sendOptOut_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.DS.project.EBankGRPC.statementResp)) {
      return super.equals(obj);
    }
    org.DS.project.EBankGRPC.statementResp other = (org.DS.project.EBankGRPC.statementResp) obj;

    boolean result = true;
    result = result && getSname()
        .equals(other.getSname());
    result = result && (getStatus()
        == other.getStatus());
    result = result && getStype()
        .equals(other.getStype());
    result = result && (getSendOptOut()
        == other.getSendOptOut());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSname().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStatus());
    hash = (37 * hash) + STYPE_FIELD_NUMBER;
    hash = (53 * hash) + getStype().hashCode();
    hash = (37 * hash) + SENDOPTOUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSendOptOut());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.DS.project.EBankGRPC.statementResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.DS.project.EBankGRPC.statementResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.DS.project.EBankGRPC.statementResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.DS.project.EBankGRPC.statementResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EBankGRPC.statementResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EBankGRPC.statementResp)
      org.DS.project.EBankGRPC.statementRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.DS.project.EBankGRPC.StatementServiceImpl.internal_static_EBankGRPC_statementResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.DS.project.EBankGRPC.StatementServiceImpl.internal_static_EBankGRPC_statementResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.DS.project.EBankGRPC.statementResp.class, org.DS.project.EBankGRPC.statementResp.Builder.class);
    }

    // Construct using org.DS.project.EBankGRPC.statementResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sname_ = "";

      status_ = false;

      stype_ = "";

      sendOptOut_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.DS.project.EBankGRPC.StatementServiceImpl.internal_static_EBankGRPC_statementResp_descriptor;
    }

    @java.lang.Override
    public org.DS.project.EBankGRPC.statementResp getDefaultInstanceForType() {
      return org.DS.project.EBankGRPC.statementResp.getDefaultInstance();
    }

    @java.lang.Override
    public org.DS.project.EBankGRPC.statementResp build() {
      org.DS.project.EBankGRPC.statementResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.DS.project.EBankGRPC.statementResp buildPartial() {
      org.DS.project.EBankGRPC.statementResp result = new org.DS.project.EBankGRPC.statementResp(this);
      result.sname_ = sname_;
      result.status_ = status_;
      result.stype_ = stype_;
      result.sendOptOut_ = sendOptOut_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.DS.project.EBankGRPC.statementResp) {
        return mergeFrom((org.DS.project.EBankGRPC.statementResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.DS.project.EBankGRPC.statementResp other) {
      if (other == org.DS.project.EBankGRPC.statementResp.getDefaultInstance()) return this;
      if (!other.getSname().isEmpty()) {
        sname_ = other.sname_;
        onChanged();
      }
      if (other.getStatus() != false) {
        setStatus(other.getStatus());
      }
      if (!other.getStype().isEmpty()) {
        stype_ = other.stype_;
        onChanged();
      }
      if (other.getSendOptOut() != false) {
        setSendOptOut(other.getSendOptOut());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.DS.project.EBankGRPC.statementResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.DS.project.EBankGRPC.statementResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sname_ = "";
    /**
     * <code>string sname = 4;</code>
     */
    public java.lang.String getSname() {
      java.lang.Object ref = sname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSnameBytes() {
      java.lang.Object ref = sname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sname = 4;</code>
     */
    public Builder setSname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sname = 4;</code>
     */
    public Builder clearSname() {
      
      sname_ = getDefaultInstance().getSname();
      onChanged();
      return this;
    }
    /**
     * <code>string sname = 4;</code>
     */
    public Builder setSnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sname_ = value;
      onChanged();
      return this;
    }

    private boolean status_ ;
    /**
     * <code>bool status = 5;</code>
     */
    public boolean getStatus() {
      return status_;
    }
    /**
     * <code>bool status = 5;</code>
     */
    public Builder setStatus(String sStatus) {
      
      status_ = sStatus;
      onChanged();
      return this;
    }
    /**
     * <code>bool status = 5;</code>
     */
    public Builder clearStatus() {
      
      status_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object stype_ = "";
    /**
     * <code>string stype = 6;</code>
     */
    public java.lang.String getStype() {
      java.lang.Object ref = stype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stype = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStypeBytes() {
      java.lang.Object ref = stype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stype = 6;</code>
     */
    public Builder setStype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stype = 6;</code>
     */
    public Builder clearStype() {
      
      stype_ = getDefaultInstance().getStype();
      onChanged();
      return this;
    }
    /**
     * <code>string stype = 6;</code>
     */
    public Builder setStypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stype_ = value;
      onChanged();
      return this;
    }

    private boolean sendOptOut_ ;
    /**
     * <code>bool sendOptOut = 7;</code>
     */
    public boolean getSendOptOut() {
      return sendOptOut_;
    }
    /**
     * <code>bool sendOptOut = 7;</code>
     */
    public Builder setSendOptOut(boolean value) {
      
      sendOptOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool sendOptOut = 7;</code>
     */
    public Builder clearSendOptOut() {
      
      sendOptOut_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

	public Builder setOpt(String opt) {
		// TODO Auto-generated method stub
		return null;
	}


    // @@protoc_insertion_point(builder_scope:EBankGRPC.statementResp)
  }

  // @@protoc_insertion_point(class_scope:EBankGRPC.statementResp)
  private static final org.DS.project.EBankGRPC.statementResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.DS.project.EBankGRPC.statementResp();
  }

  public static org.DS.project.EBankGRPC.statementResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<statementResp>
      PARSER = new com.google.protobuf.AbstractParser<statementResp>() {
    @java.lang.Override
    public statementResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new statementResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<statementResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<statementResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.DS.project.EBankGRPC.statementResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

