// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface userRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.userResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sname = 4;</code>
   */
  java.lang.String getSname();
  /**
   * <code>string sname = 4;</code>
   */
  com.google.protobuf.ByteString
      getSnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 activity = 6;</code>
   */
  int getActivity();
}
