// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface userRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.userResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string aname = 4;</code>
   */
  java.lang.String getAname();
  /**
   * <code>string aname = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnameBytes();

  /**
   * <code>string atype = 5;</code>
   */
  java.lang.String getAtype();
  /**
   * <code>string atype = 5;</code>
   */
  com.google.protobuf.ByteString
      getAtypeBytes();

  /**
   * <code>int32 abalance = 6;</code>
   */
  int getAbalance();
}
