// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.DS.project.EBankGRPC;

public interface ValResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EBankGRPC.ValResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 3;</code>
   */
  int getLength();
}
